"""Import admin/email-marketing/templates/base.html into the Jinja email shell.

Usage: python scripts/import_brand_email.py /path/to/admin [--check]
The admin template remains the design source; only engine-specific slots differ.
"""

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "synapse_pangea_chat/nudge_delivery/templates/brand_base.html"


def adapt(source: str) -> str:
    address_match = re.search(r"Pangea Chat, LLC<br />\s*([^<]+)", source)
    if not address_match:
        raise ValueError("Brand template company address was not found")
    address = address_match[1].strip()
    replacements = {
        "{{ .Campaign.Subject }}": "{{ title or app_name }}",
        '{{ template "content" . }}': "{% block content %}{% endblock %}",
        "{{ ManageURL }}": "{{ unsubscribe_url }}",
        "{{ TrackView }}": "",
        address: "{{ postal_address | default(brand_postal_address) }}",
        "You're receiving this email because you've previously\n                  expressed interest in Pangea Chat.<br />": "",
        "Manage preferences or unsubscribe": "Unsubscribe",
    }
    for old, new in replacements.items():
        if source.count(old) != 1:
            raise ValueError(f"Expected exactly one brand slot: {old}")
        source = source.replace(old, new)
    source = "\n".join(line.rstrip() for line in source.splitlines()) + "\n"
    return (
        "{# Generated by scripts/import_brand_email.py from "
        "pangeachat/admin email-marketing/templates/base.html. Do not edit. #}\n"
        "{% set brand_postal_address = " + json.dumps(address) + " %}\n" + source
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("admin", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = (args.admin / "email-marketing/templates/base.html").read_text()
    result = adapt(source)
    footer_start = result.index(
        '                <div\n                  class="nsf-badge"'
    )
    footer_end = result.index("              </td>", footer_start)
    footer = result[footer_start:footer_end]
    footer = footer.replace(
        '<p style="margin-top: 12px; font-size: 12px; color: #aaa">',
        '{% if show_unsubscribe | default(true) %}<p style="margin-top: 12px; font-size: 12px; color: #aaa">',
    )
    footer = footer.replace(
        '                <p style="margin-top: 16px;',
        '                {% endif %}\n                <p style="margin-top: 16px;',
    )
    preamble = "\n".join(result.splitlines()[:2]) + "\n"
    result = (
        result[:footer_start]
        + '                {% include "brand_footer.html" %}\n'
        + result[footer_end:]
    )
    outputs = {DEST: result, DEST.with_name("brand_footer.html"): preamble + footer}
    if args.check:
        if any(path.read_text() != content for path, content in outputs.items()):
            raise SystemExit(
                "Brand template differs; run import_brand_email.py without --check"
            )
        print("Brand template matches admin source")
    else:
        for path, content in outputs.items():
            path.write_text(content)
        print(
            f"Imported brand template (source SHA256 {hashlib.sha256(source.encode()).hexdigest()})"
        )


if __name__ == "__main__":
    main()
